// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX039V13gQ_STCcFLoCUsavplueDxdwTs',
    appId: '1:387825747305:web:5b1939fb89f10bac7b29f8',
    messagingSenderId: '387825747305',
    projectId: 'smart-agriculture-3816e',
    authDomain: 'smart-agriculture-3816e.firebaseapp.com',
    databaseURL: 'https://smart-agriculture-3816e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-agriculture-3816e.firebasestorage.app',
    measurementId: 'G-9BMC6WY18D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHowIZG2gE3W20hVXl-Q4eE8dz7sjut_c',
    appId: '1:387825747305:android:2e04c9546bac7bfe7b29f8',
    messagingSenderId: '387825747305',
    projectId: 'smart-agriculture-3816e',
    databaseURL: 'https://smart-agriculture-3816e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-agriculture-3816e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVcXehB_gXUVWcaIhcMlz9TBv1dfs8PjM',
    appId: '1:387825747305:ios:f8e4dbdf50ec30807b29f8',
    messagingSenderId: '387825747305',
    projectId: 'smart-agriculture-3816e',
    databaseURL: 'https://smart-agriculture-3816e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-agriculture-3816e.firebasestorage.app',
    iosBundleId: 'com.abhion.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX039V13gQ_STCcFLoCUsavplueDxdwTs',
    appId: '1:387825747305:web:08da87cfa32571587b29f8',
    messagingSenderId: '387825747305',
    projectId: 'smart-agriculture-3816e',
    authDomain: 'smart-agriculture-3816e.firebaseapp.com',
    databaseURL: 'https://smart-agriculture-3816e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-agriculture-3816e.firebasestorage.app',
    measurementId: 'G-QYF5R9757Q',
  );
}
